#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) 
SCREEN_NAME="reactor_simulator"

restart_command='./gradlew clean run\n'

if [ $(screen -ls | grep $SCREEN_NAME | wc -l) -gt 0 ]; then
  screen -x $SCREEN_NAME -p 0 -X stuff ''
else 
  screen -S $SCREEN_NAME -d -m /bin/bash
fi

screen -S $SCREEN_NAME -X stuff "$restart_command"
